-- MySQL Script generated by MySQL Workbench
-- Sun Feb 16 19:17:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Owner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `Owner_ID` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `contact_number` CHAR(10) NOT NULL,
  PRIMARY KEY (`Owner_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pet` (
  `Pet_ID` INT NOT NULL AUTO_INCREMENT,
  `Owner_ID` INT NOT NULL,
  `pet_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `breed_ID` INT NOT NULL,
  `breed_description` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `color_markings` VARCHAR(45) NOT NULL,
  `neutered_spayed` VARCHAR(45) NOT NULL,
  `Owner_Owner_ID` INT NOT NULL,
  PRIMARY KEY (`Pet_ID`, `Owner_ID`, `Owner_Owner_ID`),
  INDEX `fk_Pet_Owner1_idx` (`Owner_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pet_Owner1`
    FOREIGN KEY (`Owner_Owner_ID`)
    REFERENCES `mydb`.`Owner` (`Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Visit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Visit` (
  `visit_number` INT NOT NULL AUTO_INCREMENT,
  `pet_ID` INT NOT NULL,
  `date` DATE NOT NULL,
  `Weight` DECIMAL(3,2) NOT NULL,
  `temp` DECIMAL(3) NOT NULL,
  `BP` INT NOT NULL,
  `pulse` INT NOT NULL,
  `respiration` INT NOT NULL,
  `pain` INT NOT NULL,
  `vet_initials` VARCHAR(45) NOT NULL,
  `fecal_exam_results` VARCHAR(45) NOT NULL,
  `fecal_exam_notes` VARCHAR(45) NOT NULL,
  `heartworm_test_results` VARCHAR(45) NOT NULL,
  `heartworm_test_notes` VARCHAR(45) NOT NULL,
  `allergy_name1` VARCHAR(45) NOT NULL,
  `allergy_notes1` VARCHAR(45) NOT NULL,
  `allergy_name2` VARCHAR(45) NOT NULL,
  `allergy_notes2` VARCHAR(45) NOT NULL,
  `time_spent_outside` DECIMAL NOT NULL,
  `pet_diet` VARCHAR(45) NOT NULL,
  `owner_signiture` VARCHAR(45) NOT NULL,
  `date_signed` DATE NOT NULL,
  `Pet_Pet_ID` INT NOT NULL,
  `Pet_Owner_ID` INT NOT NULL,
  PRIMARY KEY (`visit_number`, `pet_ID`, `Pet_Pet_ID`, `Pet_Owner_ID`),
  INDEX `fk_Visit_Pet1_idx` (`Pet_Pet_ID` ASC, `Pet_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Visit_Pet1`
    FOREIGN KEY (`Pet_Pet_ID` , `Pet_Owner_ID`)
    REFERENCES `mydb`.`Pet` (`Pet_ID` , `Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Surgical_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Surgical_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Surgical_history` (
  `procedure` VARCHAR(45) NOT NULL,
  `pet_ID` INT NOT NULL,
  `date` DATE NULL,
  `details_notes` VARCHAR(45) NULL,
  `Pet_Pet_ID` INT NOT NULL,
  `Pet_Owner_ID` INT NOT NULL,
  PRIMARY KEY (`procedure`, `pet_ID`, `Pet_Pet_ID`, `Pet_Owner_ID`),
  INDEX `fk_Surgical_history_Pet1_idx` (`Pet_Pet_ID` ASC, `Pet_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Surgical_history_Pet1`
    FOREIGN KEY (`Pet_Pet_ID` , `Pet_Owner_ID`)
    REFERENCES `mydb`.`Pet` (`Pet_ID` , `Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vaccination_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination_history` (
  `vaccine_Id` INT NOT NULL AUTO_INCREMENT,
  `pet_Id` INT NOT NULL,
  `vaccine_type(FK)` VARCHAR(45) NULL,
  `vaccine_date` DATE NULL,
  `vaccine_next_due` DATE NULL,
  `Pet_Pet_ID` INT NULL,
  `Pet_Owner_ID` INT NULL,
  PRIMARY KEY (`vaccine_Id`, `pet_Id`, `Pet_Pet_ID`, `Pet_Owner_ID`),
  INDEX `fk_Vaccination_history_Pet1_idx` (`Pet_Pet_ID` ASC, `Pet_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccination_history_Pet1`
    FOREIGN KEY (`Pet_Pet_ID` , `Pet_Owner_ID`)
    REFERENCES `mydb`.`Pet` (`Pet_ID` , `Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vaccination` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination` (
  `vaccination_type` VARCHAR(45) NOT NULL,
  `vaccination_details` VARCHAR(45) NULL,
  `Vaccination_history_vaccine_Id` INT NOT NULL,
  `Vaccination_history_pet_Id` INT NOT NULL,
  PRIMARY KEY (`vaccination_type`),
  INDEX `fk_Vaccination_Vaccination_history1_idx` (`Vaccination_history_vaccine_Id` ASC, `Vaccination_history_pet_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccination_Vaccination_history1`
    FOREIGN KEY (`Vaccination_history_vaccine_Id` , `Vaccination_history_pet_Id`)
    REFERENCES `mydb`.`Vaccination_history` (`vaccine_Id` , `pet_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
