-- MySQL Script generated by MySQL Workbench
-- Sat Mar  7 14:24:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Owner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `Owner_ID` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `contact_number` CHAR(10) NOT NULL,
  PRIMARY KEY (`Owner_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pet` (
  `Pet_ID` INT NOT NULL AUTO_INCREMENT,
  `Owner_ID` INT NOT NULL,
  `pet_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `breed_ID` INT NOT NULL,
  `breed_description` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `color_markings` VARCHAR(45) NOT NULL,
  `neutered_spayed` VARCHAR(45) NOT NULL,
  `Owner_Owner_ID` INT NOT NULL,
  PRIMARY KEY (`Pet_ID`, `Owner_ID`, `Owner_Owner_ID`),
  INDEX `fk_Pet_Owner1_idx` (`Owner_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pet_Owner1`
    FOREIGN KEY (`Owner_Owner_ID`)
    REFERENCES `mydb`.`Owner` (`Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet Training`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pet Training` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pet Training` (
  `Class_id` VARCHAR(45) NOT NULL,
  `signature` VARCHAR(45) NOT NULL,
  `Pet_Pet_ID` INT NOT NULL,
  `Pet_Owner_ID` INT NOT NULL,
  `Pet_Owner_Owner_ID` INT NOT NULL,
  PRIMARY KEY (`Class_id`, `Pet_Pet_ID`, `Pet_Owner_ID`, `Pet_Owner_Owner_ID`),
  INDEX `fk_Pet Training_Pet1_idx` (`Pet_Pet_ID` ASC, `Pet_Owner_ID` ASC, `Pet_Owner_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pet Training_Pet1`
    FOREIGN KEY (`Pet_Pet_ID` , `Pet_Owner_ID` , `Pet_Owner_Owner_ID`)
    REFERENCES `mydb`.`Pet` (`Pet_ID` , `Owner_ID` , `Owner_Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Class_Type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Class_Type` (
  `date` DATE NOT NULL,
  `Pet Training_Class_id` VARCHAR(45) NOT NULL,
  `Pet Training_Pet_Pet_ID` INT NOT NULL,
  `Pet Training_Pet_Owner_ID` INT NOT NULL,
  `Pet Training_Pet_Owner_Owner_ID` INT NOT NULL,
  PRIMARY KEY (`date`, `Pet Training_Class_id`, `Pet Training_Pet_Pet_ID`, `Pet Training_Pet_Owner_ID`, `Pet Training_Pet_Owner_Owner_ID`),
  INDEX `fk_Class_Type_Pet Training1_idx` (`Pet Training_Class_id` ASC, `Pet Training_Pet_Pet_ID` ASC, `Pet Training_Pet_Owner_ID` ASC, `Pet Training_Pet_Owner_Owner_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Class_Type_Pet Training1`
    FOREIGN KEY (`Pet Training_Class_id` , `Pet Training_Pet_Pet_ID` , `Pet Training_Pet_Owner_ID` , `Pet Training_Pet_Owner_Owner_ID`)
    REFERENCES `mydb`.`Pet Training` (`Class_id` , `Pet_Pet_ID` , `Pet_Owner_ID` , `Pet_Owner_Owner_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
